---
- hosts: centreon-web

  tasks:
    - name: add package necessary to manage selinux (if enabled)
      yum:
        name: libselinux-python
        state: present
      when: ansible_distribution == "CentOS"
    - name: disable selinux (default)
      selinux:
        state: disabled
      when: ansible_distribution == "CentOS"

    - name: add repo centreon centos6
      get_url:
        url: http://yum.centreon.com/standard/3.4/el6/stable/centreon-stable.repo
        dest: /etc/yum.repos.d
        mode: 0644
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

    - name: add repo centreon centos7
      get_url:
        url: http://yum.centreon.com/standard/3.4/el7/stable/centreon-stable.repo
        dest: /etc/yum.repos.d
        mode: 0644
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

    - name: add rpm key to centreon repository (CentOS6)
      rpm_key:
        state: present
        key: http://yum.centreon.com/standard/3.4/el6/stable/RPM-GPG-KEY-CES
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

    - name: add rpm key to centreon repository (CentOS7)
      rpm_key:
        state: present
        key: http://yum.centreon.com/standard/3.4/el7/stable/RPM-GPG-KEY-CES
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

    - name: install centreon web and requirements
      yum:
        name:
          - centreon-base-config-centreon-engine
          - centreon
          - MariaDB-server
        state: latest

    - name: php timezone configuration
      copy:
        dest: /etc/php.d/php-timezone.ini
        content: |
          date.timezone = Europe/Paris

    - name: Generate SSH keys
      shell: su - centreon -c 'ssh-keygen -t rsa -f /var/spool/centreon/.ssh/id_rsa -q -N ""'
      args:
        creates: /var/spool/centreon/.ssh/id_rsa

    - name: Enable services necessary to use Centreon
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        services:
          - httpd
          - snmpd
          - mysql
          - centcore
          - cbd
          - centengine
